openapi: 3.0.0
info:
  version: 0.0.0
  title: test
paths:
  /callback:
    post:
      summary: Subscribe to a webhook
      operationId: callback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                callbackUrl:   # Callback URL
                  type: string
                  format: uri
                  example: https://myserver.com/send/callback/here
                data:
                  type: object
              required:
                - callbackUrl
                - eventType
                - eventSource
      responses:
        '201':
          description: Webhook created
      callbacks:   # Callback definition
        myEvent:   # Event name
          '{$request.body#/callbackUrl}':   # The callback URL,
                                            # Refers to the passed URL
            post:
              requestBody:   # Contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      type: object
              responses:   # Expected responses to the callback message
                '200':
                  description: Your server returns this code if it accepts the callback
 