/*
 * test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject1 struct {

	Message string `json:"message"`
}

// AssertInlineObject1Required checks if the required fields are not zero-ed
func AssertInlineObject1Required(obj InlineObject1) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseInlineObject1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineObject1 (e.g. [][]InlineObject1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineObject1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineObject1, ok := obj.(InlineObject1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineObject1Required(aInlineObject1)
	})
}
