openapi: 3.0.0
info:
  title: test
  version: 0.0.0
servers:
- url: /
paths:
  /callback:
    post:
      callbacks:
        myEvent:
          '{$request.body#/callbackUrl}':
            post:
              operationId: myEvent_Post
              requestBody:
                $ref: '#/components/requestBodies/inline_object_1'
                content:
                  application/json:
                    schema:
                      properties:
                        message:
                          example: Some event happened
                          type: string
                      required:
                      - message
                      type: object
                required: true
              responses:
                "200":
                  description: Your server returns this code if it accepts the callback
              x-callback-request: true
      operationId: callback
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                callbackUrl:
                  example: https://myserver.com/send/callback/here
                  format: uri
                  type: string
                eventType:
                  type: string
                eventId:
                  type: string
                eventSource:
                  type: string
                workflowData:
                  type: object
              required:
              - callbackUrl
              - eventId
              - eventSource
              - eventType
              - workflowData
              type: object
        required: true
      responses:
        "201":
          description: Webhook created
      summary: Subscribe to a webhook
components:
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
      required: true
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    inline_object_1:
      properties:
        message:
          example: Some event happened
          type: string
      required:
      - message
      type: object
    inline_object:
      properties:
        callbackUrl:
          example: https://myserver.com/send/callback/here
          format: uri
          type: string
        eventType:
          type: string
        eventId:
          type: string
        eventSource:
          type: string
        workflowData:
          type: object
      required:
      - callbackUrl
      - eventId
      - eventSource
      - eventType
      - workflowData
      type: object
